first_number = int(input())
second_number = int(input())
third_number = int(input())
forth_number = int(input())
total_sum = (((first_number + second_number) // third_number) * forth_number)
print(total_sum)